export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const DISMISS_NOTIFICATION = 'DISMISS_NOTIFICATION';

// UI
export const TOGGLE_TRANSACTIONS_FILTER = 'TOGGLE_TRANSACTIONS_FILTER';
