export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const SET_CONTACTS = 'SET_CONTACTS';

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const DISMISS_NOTIFICATION = 'DISMISS_NOTIFICATION';

export const OPEN_DIALOG = 'OPEN_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';

// UI
export const TOGGLE_TRANSACTIONS_FILTER = 'TOGGLE_TRANSACTIONS_FILTER';
