export const SET_CORE_INFO = 'SET_CORE_INFO';
export const CLEAR_CORE = 'CLEAR_CORE';

export const SET_USER_STATUS = 'SET_USER_STATUS';
export const CLEAR_USER = 'CLEAR_USER';

export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const SET_CONTACTS = 'SET_CONTACTS';

// UI
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const DISMISS_NOTIFICATION = 'DISMISS_NOTIFICATION';

export const OPEN_DIALOG = 'OPEN_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';

export const TOGGLE_TRANSACTIONS_FILTER = 'TOGGLE_TRANSACTIONS_FILTER';
export const SEARCH_CONTACTS = 'SEARCH_CONTACTS';
