export default {
  AUD: 'Australian Dollar (AUD)',
  BTC: 'Bitcoin (BTC)',
  BRL: 'Brazilian Real (BRL)',
  GBP: 'British Pound (GBP)',
  MMK: 'Burmese Kyat (MMK)',
  CAD: 'Canadian Dollar (CAD)',
  CLP: 'Chilean Peso (CLP)',
  CNY: 'Chinese Yuan (CNY)',
  CZK: 'Czeck Koruna (CZK)',
  EUR: 'Euro (EUR)',
  HKD: 'Hong Kong Dollar (HKD)',
  ILS: 'Israeli Shekel (ILS)',
  INR: 'Indian Rupee (INR)',
  IDR: 'Indonesian Rupiah (IDR)',
  JPY: 'Japanese Yen (JPY)',
  KRW: 'Korean Won (KRW)',
  MYR: 'Malaysian Ringgit (MYR)',
  MXN: 'Mexican Peso (MXN)',
  NZD: 'New Zealand Dollar (NZD)',
  PKR: 'Pakistan Rupee (PKR)',
  PHP: 'Philippine Peso (PHP)',
  PLN: 'Polish Złoty (PLN)',
  RUB: 'Russian Ruble (RUB)',
  SAR: 'Saudi Riyal (SAR)',
  SGD: 'Singapore Dollar (SGD)',
  ZAR: 'South African Rand (ZAR)',
  CHF: 'Swiss Franc (CHF)',
  TWD: 'Taiwan Dollar (TWD)',
  THB: 'Thai Baht (THB)',
  AED: 'United Arab Emirates Dirham (AED)',
  USD: 'United States Dollar (USD)',
  VND: 'Vietnamese Dong (VND)',
};
